import { createOptimizedPicture } from '../../scripts/aem.js';

/**
 * Article List Block — dynamic, index-driven.
 *
 * Renders a responsive grid of article cards built LIVE from the site's
 * query index (`/query-index.json`, generated by helix-query.yaml). Because it
 * reads the published index at runtime, newly published articles appear
 * automatically with no code change.
 *
 * Document table structure (all rows optional):
 *   Row 1: path filter   e.g. "/magazine/" (defaults to /magazine/)
 *   Row 2: limit         e.g. "6"          (max cards to show; default all)
 *   Row 3: category      e.g. "Travel"     (filter by category metadata)
 */
export default async function decorate(block) {
  // 1. Read authored configuration (graceful defaults if omitted)
  const rows = [...block.children];
  const cfg = rows.map((r) => r.textContent.trim()).filter(Boolean);
  const pathPrefix = cfg[0] || '/magazine/';
  const limit = Number.parseInt(cfg[1], 10) || 0;
  const category = cfg[2] || '';

  block.textContent = '';
  block.setAttribute('aria-busy', 'true');

  // 2. Fetch the live index
  let articles = [];
  try {
    const resp = await fetch('/query-index.json');
    if (resp.ok) {
      const json = await resp.json();
      articles = json.data || [];
    }
  } catch (e) {
    // network / offline — render nothing rather than break the page
    articles = [];
  }

  // 3. Filter + sort (newest first)
  articles = articles
    .filter((a) => a.path && a.path.startsWith(pathPrefix) && a.path !== pathPrefix)
    .filter((a) => !category || (a.category || '').toLowerCase() === category.toLowerCase())
    .sort((a, b) => {
      const da = Date.parse(a.publisheddate) || Number(a.lastModified) * 1000 || 0;
      const db = Date.parse(b.publisheddate) || Number(b.lastModified) * 1000 || 0;
      return db - da;
    });

  if (limit > 0) articles = articles.slice(0, limit);

  // 4. Build the DOM
  const ul = document.createElement('ul');
  ul.className = 'article-list-items';

  articles.forEach((article) => {
    const li = document.createElement('li');
    li.className = 'article-list-card';

    const link = document.createElement('a');
    link.href = article.path;
    link.setAttribute('aria-label', article.title || 'Read article');

    if (article.image) {
      const imgWrap = document.createElement('div');
      imgWrap.className = 'article-list-card-image';
      const picture = createOptimizedPicture(article.image, article.title || '', false, [{ width: '750' }]);
      imgWrap.append(picture);
      link.append(imgWrap);
    }

    const body = document.createElement('div');
    body.className = 'article-list-card-body';

    if (article.category) {
      const cat = document.createElement('span');
      cat.className = 'article-list-card-category';
      cat.textContent = article.category;
      body.append(cat);
    }

    const h = document.createElement('h3');
    h.className = 'article-list-card-title';
    h.textContent = article.title || 'Untitled';
    body.append(h);

    if (article.description) {
      const p = document.createElement('p');
      p.className = 'article-list-card-desc';
      p.textContent = article.description;
      body.append(p);
    }

    if (article.author) {
      const meta = document.createElement('p');
      meta.className = 'article-list-card-meta';
      meta.textContent = article.publisheddate
        ? `${article.author} · ${article.publisheddate}`
        : article.author;
      body.append(meta);
    }

    link.append(body);
    li.append(link);
    ul.append(li);
  });

  if (!articles.length) {
    const empty = document.createElement('p');
    empty.className = 'article-list-empty';
    empty.textContent = 'No articles found yet. Publish a page under this section to see it here.';
    block.append(empty);
  } else {
    block.append(ul);
  }

  block.removeAttribute('aria-busy');
}
